### PR TITLE
release/v24.10.0

### PR DESCRIPTION
**Pull request by abhatthal**
release/v0.1.0 contains the following features and bug fixes
- Added support for Apple Silicon Macs
- Create Windows batch script launcher
- Upgraded all platforms to VTK9.1
- Updated README with packaging instructions and releases
- Fix get memory bug in do_launch script for macOS
- New VTK interface introduces backwards incompatible changes. Updated our calls (i.e. GetNumberOfPoints()) to use the updated types

### CODE REVIEW

**Comment by abhatthal** [comment]
I found on scecvdo.usc.edu (Recently spun up) that the previous stable release was at v19.8.
I think we should rename this to v19.9.0 respectively.

**Comment by kevinmilner** [comment]
> I found on scecvdo.usc.edu (Recently spun up) that the previous stable release was at v19.8. I think we should rename this to v19.9.0 respectively.

The "19.8" probably refers to August, 2019. We use that sort of versioning for a lot of projects (e.g., CyberShake studies). So I propose calling this v24.10.0 instead.

**Comment by abhatthal** [comment]
Agreed, v24.10.0 for October 2024 release. I updated the SCECpedia and download links respectively.

**Comment by kevinmilner** [comment]
Just checked it out and things look pretty good, except I had trouble building with ant, but that's not your fault (see below). Can you do the following:

- update the  "target" and "source" versions in build.xml to 11 (from 1.7). That's the java version, and since VDO relies on OpenSHA which in tern is on java 11, that needs to be the minimum
- update the classpath in build.xml to match the current jars; there are a few missing and a few extras
- merge in the commit I just made to master with an updated opensha jar file, and the missing GridSourcesAnim that was causing compilation problems
- make sure that `ant build` works to compile it without eclipse. Maybe test this with a clean clone, e.g., clone your branch and run `and build`, then verify that it succeeded and running the launcher script launches it

Thanks!

**Pull request closed without merging**
